extends: capitalization
message: "'%s' should be in heading case."
link: 'https://docs.mongodb.com/meta/style-guide/style/titles-and-headings/'
level: error
scope: heading
match: $title
style: Chicago