name: vale-checks
on:
  push:
    branches-ignore:
      - master

jobs:
  vale:
    name: TDBX Vale rules
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@master

      - name: tdbx-vale-check
        uses: errata-ai/vale-action@reviewdog
        with:
          files: source/
          reporter: github-pr-check
          fail_on_error: true
          filter_mode: file
          token: ${{secrets.GITHUB_TOKEN}}
