name: vale-checks
on:
  push:
    branches-ignore:
      - master
with:
  version: 2.17.0
  files: source/
  reporter: github-pr-check

jobs:
  vale:
    name: TDBX Vale rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
