name: vale-checks
on:
  push:
    branches-ignore:
      - master

jobs:
  vale:
    name: TDBX Vale rules
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: tdbx-vale
        uses: errata-ai/vale-action@reviewdog
        with:
          reporter: github-pr-check
          files: source
          fail_on_error: true
          filter_mode: diff_context
          token: ${{secrets.GITHUB_TOKEN}}
