name: vale-checks
on:
  push:
    branches-ignore:
      - master

jobs:
  vale:
    name: TDBX Vale rules
    runs-on: ubuntu-latest
    steps:
      - name: checkout

        uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: true
          filter_mode: diff_context
          vale_flags: "--config .vale.ini"
          token: ${{secrets.GITHUB_TOKEN}}

