name: vale-checks
on:
  push:
    branches-ignore:
      - master

jobs:
  vale:
    name: TDBX Vale rules
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@master


      - name: tdbx-vale-check
        uses: errata-ai/vale-action@v1.4.0
        with:
          files: __onlyModified
