name: vale-checks
on:
  push:
    branches-ignore:
      - master

jobs:
  vale:
    name: TDBX Vale rules
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Changed files
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
          echo "::set-output name=ts::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .ts$ | xargs)"

      - name: tdbx-vale
        uses: errata-ai/vale-action@reviewdog
        with:
          reporter: github-pr-check
          files: source
          fail_on_error: true
          filter_mode: diff_context
          token: ${{secrets.GITHUB_TOKEN}}
